### ISSUE TITLE
Deploy FireCamp into existing VPC

### ISSUE THREAD

**Issue by calvinlfer** [cloudstax/firecamp#1]
Hello,

Is it possible to deploy a FireCamp cluster into an existing VPC?

Thanks
Cal

**Comment by JuniusLuo** [comment]
Thanks for the question. Yes, you could try the test template packaging/aws-cloudformation/firecamp-test.template. It is included in every release, such as https://s3.amazonaws.com/cloudstax/firecamp/releases/0.8.0/cf-templates/firecamp-test.template. Currently we use it for test only. 
You would have to specify the availability zones and the corresponding subnet ids. And you need to pay attention to the security. The "RemoteAccessCIDR" are allowed to SSH to the service nodes. It is better to not open the SSH to the external internet. The ports 2000~30000 are opened to the "AppAccessSecurityGroup", which could be fixed.

**Comment by calvinlfer** [comment]
Sounds great, thanks!

**Comment by cloudstax** [comment]
I am closing this issue. If you have further enhancement requirement for the template, please create new issue for it. Thanks!

**Comment by cloudstax** [comment]
The test template is renamed to firecamp-existingvpc.template in release 0.8.1 and latest.
