### ISSUE TITLE
Kafka logs flooding

### ISSUE THREAD

**Issue by jazzl0ver** [cloudstax/firecamp#10]
Hi. Found a lot of such messages in the logs (CloudWatch):
```
[2017-11-29 22:43:58,934] INFO [GroupMetadataManager brokerId=2] Removed 0 expired offsets in 0 milliseconds. (kafka.coordinator.group.GroupMetadataManager)
```
Is there an option to stop flooding like this?

**Comment by JuniusLuo** [comment]
Could you please post more logs? How often the messages are logged? like every second?

**Comment by jazzl0ver** [comment]
Every 10 minutes:
![image](https://user-images.githubusercontent.com/2444175/33476139-f49fa358-d691-11e7-8336-ccd99662612f.png)

**Comment by JuniusLuo** [comment]
Thanks for posting the detail logs! This looks ok. It is only logged 1 message every 10 minutes. This would be the expected behaviour of Kafka. 

If you still have concern about it, it would be better to ask Kafka guys :)

**Comment by jazzl0ver** [comment]
Thank you, @JuniusLuo !
