### ISSUE TITLE
0.9.2 release fails to launch in AWS

### ISSUE THREAD

**Issue by jazzl0ver** [cloudstax/firecamp#17]
Used template firecamp-existingvpc.template. At some point cloudformation stack creation fails at the ASG initialization. Was able to find what's going on:
```
[root@ip-172-31-38-80 tmp]# docker plugin install --grant-all-permissions cloudstax/firecamp-log:0.9.2 CLUSTER="firecamp-prod"
0.9.2: Pulling from cloudstax/firecamp-log
481765f73fa2: Download complete
Digest: sha256:fb14fb10d55f7e78d65b1e874ee036844a0f5552074c9c94b1715695286e723a
Status: Downloaded newer image for cloudstax/firecamp-log:0.9.2
Error response from daemon: setting "CLUSTER" not found in the plugin configuration
```

The latest release installs w/o issues:
```
[root@ip-172-31-38-80 tmp]# docker plugin install --grant-all-permissions cloudstax/firecamp-log:latest CLUSTER="firecamp-prod"
latest: Pulling from cloudstax/firecamp-log
1c827c905aed: Download complete
Digest: sha256:809700ced49e4b477f5ff42f9a6ec4bdb3e649982bf91913f3f865afad932a2d
Status: Downloaded newer image for cloudstax/firecamp-log:latest
Installed plugin cloudstax/firecamp-log:latest
```

Please, fix

**Comment by JuniusLuo** [comment]
Sorry for breaking thing. We were developing the log plugin to become service member aware. It happened to break the ecs-agent image. The fix was committed to ecs-agent branch last night. Could you please try it again for release 0.9.2? It should be good now. I just launched a testbed. There is no need to install the log plugin for 0.9.2.

**Comment by JuniusLuo** [comment]
Did you get the chance to try it again?

**Comment by jazzl0ver** [comment]
Sorry for the delay. It's failed again

**Comment by JuniusLuo** [comment]
Could you please share your configs? Sounds you didn't set QSS3KeyPrefix correctly. You need to set "Release" to "0.9.2", and "QSS3KeyPrefix" to "firecamp/releases/0.9.2/". 

Are you using https://s3.amazonaws.com/cloudstax/firecamp/releases/0.9.2/templates/firecamp-master.template?

**Comment by jazzl0ver** [comment]
oops. you're right. i missed that parameter. don't you think it should automatically substitute the version into "QSS3KeyPrefix" value?

**Comment by JuniusLuo** [comment]
Ideally, yes. But it is not easy to do this in CloudFormation...

**Comment by JuniusLuo** [comment]
Or you could simply use https://s3.amazonaws.com/cloudstax/firecamp/releases/0.9.2/templates/firecamp-master.template, which already sets both Release and QSS3KeyPrefix to 0.9.2.

**Comment by jazzl0ver** [comment]
yeah, good point. thank you!
