### ISSUE TITLE
Having trouble building firecamp-service-cli 0.9.0 from source

### ISSUE THREAD

**Issue by vumanhcuongit** [cloudstax/firecamp#2]
The S3 CLI link as stated on [`master`'s README.md](https://github.com/cloudstax/firecamp#installation) uses CLI version 0.8.0; however, following through [the tutorial on setting up a Cassandra cluster](https://github.com/cloudstax/firecamp/wiki/Tutorials#cassandra-tutorials), there's a flag that only gets supposed in the 0.9.0 release: `-journal-volume-size`

```
firecamp-service-cli -op=create-service -service-type=cassandra -region=us-east-1 -cluster=t1 -service-name=mycas -replicas=3 -volume-size=100 -journal-volume-size=10
```

I've been trying to build the CLI from source on my local machine yet have been seeing issues with the `aws/session` package:

```
root@8d9d88564e5c:/usr/src/firecamp-service-cli# go build -v
_/usr/src/firecamp-service-cli
# _/usr/src/firecamp-service-cli
./main.go:1182:36: cannot use sess (type *"github.com/aws/aws-sdk-go/aws/session".Session) as type *"github.com/cloudstax/firecamp/vendor/github.com/aws/aws-sdk-go/aws/session".Session in argument to awsroute53.NewAWSRoute53
```

@JuniusLuo can you help with providing the latest `cli` executable or let me know how I'd fix the issue above? I came across Firecamp last night and this is a major roadblock. Thanks.

**Comment by rebyn** [comment]
@vumanhcuongit I think this link: https://s3.amazonaws.com/cloudstax/firecamp/releases/latest/packages/firecamp-service-cli.tgz would do :).

**Comment by JuniusLuo** [comment]
@vumanhcuongit thanks for reporting this issue! Will update the readme to point to the latest release.
To build the CLI, please run "make install". Then get the cli at $GOPATH/bin/firecamp-service-cli.

**Comment by JuniusLuo** [comment]
@rebyn Thanks for the help! yes, the latest package includes the new journal volume support. Could also get from https://s3.amazonaws.com/cloudstax/firecamp/releases/0.9/packages/firecamp-service-cli.tgz

**Comment by cloudstax** [comment]
The master README.md is updated to link 0.9 release. close this issue. please let us know if you hit any issue.
