### ISSUE TITLE
Volume encryption at rest for AWS

### ISSUE THREAD

**Issue by jazzl0ver** [cloudstax/firecamp#20]
Hi. Please, implement volume encryption at rest for AWS environment. Not sure if journal volumes should be encrypted. Probably not unless they contain sensitive data.

**Comment by JuniusLuo** [comment]
yes, this is on roadmap. Both journal and data volumes should be encrypted. All data is written into the journal volume first, and then to the data volume.

**Comment by jazzl0ver** [comment]
Can you please share estimates on the implementation?

**Comment by JuniusLuo** [comment]
It will probably be supported in Q2.

**Comment by JuniusLuo** [comment]
Your patch looks work. Are you able to test it? Thanks!

**Comment by jazzl0ver** [comment]
I've already tested it. Works well. One thing that I'm not able to do - implement update-volume call to convert volumes between encrypted and unencrypted state. It would be great if you take care of that!

**Comment by JuniusLuo** [comment]
There is no direct way to encrypt an existing unencrypted volume. You need to migrate data between encrypted and unencrypted volumes. See [AWS EBS Changing the Encryption State of Your Data](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/EBSEncryption.html#EBSEncryption_considerations).

You could use firecamp cli to stop all containers of the service. Then follow EBS guide to migrate data from the existing unencrypted volume to the new encrypted volume. After that, you could use the firecamp-volume-replace tool to replace the unencrypted volume with the encrypted volume. Please be careful when using the volume-replace tool. You need to make sure the volume is replaced by the correct encrypted volume. Or else, when the cluster starts, it may write additional data to the new volume.

**Comment by jazzl0ver** [comment]
Yeah, I understand that. I just thought we could automate it :)

**Comment by JuniusLuo** [comment]
yes, we may support in the future. While, this is not a simple task. It is not planned in the short term. You could create another issue to track it :)

**Comment by jazzl0ver** [comment]
Agree
