### ISSUE TITLE
Add kafka-manager

### ISSUE THREAD

**Issue by jazzl0ver** [cloudstax/firecamp#25]
Please, implement kafka-manager (https://github.com/yahoo/kafka-manager) into Kafka service creation.
A ready-to-use docker image - https://hub.docker.com/r/sheepkiller/kafka-manager/ - can be used. Probably the best way is to add a command line keys like **-enable-kafka-manager** and **-kafka-manager-port=9000** to run it along with the kafka service.

**Comment by JuniusLuo** [comment]
kafka-manager is a good project. Will further evaluate how to add it.

**Comment by JuniusLuo** [comment]
The initial Kafka Manager service is added. We decided to add as a separate service, as one Kafka Manager could manage multiple Kafka services. Please take a look and see if it works for you. Thanks!

**Comment by jazzl0ver** [comment]
It does work, awesome! Thanks a bunch!
One thing I noticed is that the log group for kafkamanager looks like *firecamp-firecamp-qa-kafkamanager-qa-b52...*, while my other loggroups looks like *firecamp-qa-kafka-qa-ae9a...*
Could you please fix loggroup name generation?
The command line for kafkamanager creation was:
```
./firecamp-service-cli -cluster=firecamp-qa -region=us-east-1 -op=create-service -service-type=kafkamanager -service-name=kafkamanager-qa -km-heap-size=512 -km-zk-service=zoo-qa
```

**Comment by jazzl0ver** [comment]
Please, add Kafka Manager readme to the tutorials wiki page

**Comment by JuniusLuo** [comment]
yes, the log group format is firecamp-clustername-servicename-serviceuuid. Your cluster name is "firecamp-qa", so the log group name will start with firecamp-firecamp-qa.

**Comment by JuniusLuo** [comment]
Thanks for the remind! Added to wiki.

**Comment by jazzl0ver** [comment]
> yes, the log group format is firecamp-clustername-servicename-serviceuuid. Your cluster name is "firecamp-qa", so the log group name will start with firecamp-firecamp-qa.

it used to be different before, right? the point is that i name my clusters like 'firecamp-uat' or 'firecamp-qa' to differentiate them from other clusters like 'uat' and 'qa' where the apps are running.
could you please revert that back and name log groups after the cluster name w/o any prefixes? this is really more logical than the current implementation (imho).

**Comment by JuniusLuo** [comment]
yes, the firecamp prefix is added recently. sounds a good suggstion. we could revert it.

**Comment by JuniusLuo** [comment]
The fix was committed.
