### ISSUE TITLE
Cassandra: OpenJDK vs Oracle Java

### ISSUE THREAD

**Issue by jazzl0ver** [cloudstax/firecamp#30]
There is a warning in the log:
```
WARN [main] 2018-02-13 10:16:44,908 StartupChecks.java:203 - OpenJDK is not recommended. Please upgrade to the newest Oracle Java release
```
Do you think we need to switch to Oracle Java?

**Comment by JuniusLuo** [comment]
It would be ok to use openjdk. The core of openjdk would be the same with oracle java. [Cassandra recommended settings](https://docs.datastax.com/en/dse/5.1/dse-dev/datastax_enterprise/config/configRecommendedSettings.html) lists openjdk as well. 

 The official cassandra docker image uses the openjdk as well. Unless there is a specific reason, we will keep the same with the official docker image.

**Comment by jazzl0ver** [comment]
Wondering why it alarms in the log then :) Thanks for clarification.
