### ISSUE TITLE
Cassandra: incremental backup

### ISSUE THREAD

**Issue by jazzl0ver** [cloudstax/firecamp#32]
```
$ cat cassandra.yaml
...
incremental_backups: false
```
Is it false intentionally?

**Comment by JuniusLuo** [comment]
The false is the default value for incremental_backups. If this is enabled, you will have to manage the flushed sstable links by yourselves. Do you have the requirements to enable it?

Below are the detail comments in cassandra.yaml
# Set to true to have Cassandra create a hard link to each sstable
# flushed or streamed locally in a backups/ subdirectory of the
# keyspace data.  Removing these links is the operator's
# responsibility.

**Comment by jazzl0ver** [comment]
No, I don't. Just found out that while discovering backup tools which supports incremental backups. Thanks for explanation!

**Comment by JuniusLuo** [comment]
yes, we will further evaluate the backup solution. If the backup requires to enable the incremental_backups, we will enable it.
