### ISSUE TITLE
aws quickstart template misses latest version

### ISSUE THREAD

**Issue by jazzl0ver** [cloudstax/firecamp#36]
https://s3.amazonaws.com/quickstart-reference/cloudstax/firecamp/latest/templates/firecamp-existingvpc.template:
![image](https://user-images.githubusercontent.com/2444175/36306868-a99cc068-132a-11e8-9556-3e6449f3a6ca.png)

**Comment by JuniusLuo** [comment]
We do not want to expose the latest version to AWS QuickStart, as the latest version may not be stable. We will always put the latest release in AWS QuickStart. The QuickStart S3KeyPrefix points to AWS QuickStart S3 bucket, the path is cloudstax/firecamp/latest.

If you want to test/develop the latest version, please still use "cloudstax" bucket, https://s3.amazonaws.com/cloudstax/firecamp/releases/latest/templates/firecamp-master.template or https://s3.amazonaws.com/cloudstax/firecamp/releases/latest/templates/firecamp-existingvpc.template

**Comment by jazzl0ver** [comment]
Of course, it's completely up to you. But I'd give a user a choice of what to use. In my opinion the better way is to put a comment to avoid using latest release in production.
Also, please recall this thread: https://github.com/cloudstax/firecamp/issues/17#issuecomment-360527241: you advised to change the QSS3KeyPrefix to 0.9.2 from latest.

**Comment by JuniusLuo** [comment]
Thanks for sharing your suggestion! We still have concern for including the latest version in AWS QuickStart. None other QuickStart includes the developing release. Let's add how to install the latest version into the installation guide.

**Comment by JuniusLuo** [comment]
Updated the installation guide for installing the latest build.

**Comment by jazzl0ver** [comment]
The current quick start template still uses cloudstax/firecamp/latest as S3KeyPrefix, while the release version  either 0.9.3 or 0.9.2. Is that OK?

**Comment by JuniusLuo** [comment]
This is ok. The quickstart templates are hosted on AWS QuickStart Bucket, not cloudstax bucket. The templates in AWS QuickStart bucket has only one path, cloudstax/firecamp/latest. So the S3KeyPrefix in AWS QuickStart bucket is cloudstax/firecamp/latest. When we have a new release, the templates under cloudstax/firecamp/latest in AWS QuickStart bucket will be updated to the new release.

It is like we always put the last release (such as 0.9.3) templates under firecamp/releases/latest in the cloudstax bucket.

**Comment by jazzl0ver** [comment]
Oh, that makes sense. Though it's kinda messing. Didn't you think to sync the AWS quick start bucket name with the release version? If a user is choosing release 0.9.2 in the dropdown, will he need to change the quickstart bucket path from latest to something else?

**Comment by JuniusLuo** [comment]
Good Point!
We could not change the bucket name with the release version. This is not how AWS QuickStart works. We will need to make sure both releases work on the same templates, both 0.9.3 and 0.9.2 work on the 0.9.3's templates. This is not a hard problem. The template changes are usually small and compatible between 2 releases. Just tried to deploy 0.9.2 from AWS QuickStart, and it worked.
