### ISSUE TITLE
no service type check

### ISSUE THREAD

**Issue by jazzl0ver** [cloudstax/firecamp#60]
I accidentally forgot to change the service name and it still worked:
```
$ $PREFIX/firecamp-service-cli -op=stop-service -service-type=kafka -region=us-east-1 -cluster=firecamp-$ENV -service-name=zoo-$ENV
Service stopped
```
(Notice type=kafka and name=zoo)

**Comment by JuniusLuo** [comment]
Currently stop service does not check the service type. We could add the check for it.

**Comment by cloudstax** [comment]
1.0 check the service type for all requests. If you find any bug, please create a new issue for the request or reopen this. Thanks!
