### ISSUE TITLE
worker volumes are not tagged

### ISSUE THREAD

**Issue by jazzl0ver** [cloudstax/firecamp#61]
Please, fix

**Comment by JuniusLuo** [comment]
To confirm, you are suggesting to add tag to the EBS volume of the EC2 instance, right?

AWS CloudFormation AutoScalingGroup tags the EC2 instance, while not tag the EBS volume. We will have to add tag in the shell script, passed in user data. Will add a patch for it.

**Comment by jazzl0ver** [comment]
> To confirm, you are suggesting to add tag to the EBS volume of the EC2 instance, right?
Correct

Thank you!

**Comment by cloudstax** [comment]
1.0 supports the worker volume tag. While, the volume of the Bastion node is not tagged. The Bastion node is created by the common Bastion template, which is developed by AWS.
