### ISSUE TITLE
Parameters Allowed Pattern bug

### ISSUE THREAD

**Issue by ddt7** [cloudstax/firecamp#63]
You have set for vpc and subnet
subnet-[0-9a-z]{8}
which is not corrent since they may be longer than 8 chars
change to subnet-[0-9a-z]{8,}
or anything else that would work
is can't be run now

**Comment by JuniusLuo** [comment]
Thanks for reporting it! We also hit this in the quickstart test. It has been fixed in the quickstart git. Will port back to here.

**Comment by ddt7** [comment]
Thanks. But the cloudformation scripts in s3 are not sync with that change yet

**Comment by cloudstax** [comment]
The "latest" templates in s3 are synced. Please use 1.0 instead of latest. The latest branch is under development.
