### ISSUE TITLE
Kafkamanager does not see JMX port

### ISSUE THREAD

**Issue by jazzl0ver** [cloudstax/firecamp#70]
It shows **-1** instead:
![image](https://user-images.githubusercontent.com/2444175/44218783-1d599d00-a183-11e8-9a18-8f6ec00dd86b.png)
To fix that, the environment variable *JMX_PORT* has to be set before starting Kafka.
Please, add it to the Kafka task definition.
Probably the line should be:
```
kafkacatalog.go:
func GenDefaultCreateServiceRequest(platform string, region string, azs []string,
....
        envkvs := []*common.EnvKeyValuePair{
                &common.EnvKeyValuePair{Name: ENV_JMX_PORT, Value: jmxPort},
        }
...
```

**Comment by JuniusLuo** [comment]
JMX_PORT is included in the "service.conf". Kafka container entrypoint.sh will source the service.conf file. Kafka should already start with JMX_PORT.

KafkaManager collects the metrics via the JMX_PORT. If JMX_PORT is not set in Kafka, kafkamanager would not be able to collect the metrics. Possibly a bug in kafkamanager?

**Comment by JuniusLuo** [comment]
I see what you mean. Source the service.conf file is not enough. We have to explicitly export JMX_PORT, so kafka starting script will recognize it. We could make a fix to kafka image entrypoint.sh to export JMX_PORT, and rebuild the image. Will make a fix.
