### ISSUE TITLE
Kafka JMX port is missing in ServiceSecurityGroup

### ISSUE THREAD

**Issue by jazzl0ver** [cloudstax/firecamp#71]
```
[root@monitor-uat plugin]# telnet kafka-uat-0.firecamp-uat-firecamp.com 9092
Trying 172.22.1.107...
Connected to kafka-uat-0.firecamp-uat-firecamp.com.
Escape character is '^]'.
^]
telnet> q
Connection closed.
[root@monitor-uat plugin]# telnet kafka-uat-0.firecamp-uat-firecamp.com 9093
Trying 172.22.1.107...
^C
```

**Comment by JuniusLuo** [comment]
This is by design. We limit the Kafka jmx port to kafkamanager only. Is there any reason that you want to connect to it instead of viewing in kafkamanager?

**Comment by jazzl0ver** [comment]
Same reason like we have for Cassandra - retrieve various counters and set up alarms in the monitoring system. Kafkamanager is unable to send alerts.

**Comment by JuniusLuo** [comment]
Sounds good. We could open it.
