### ISSUE TITLE
The following resource(s) failed to create: [LambdaCustomResource]

### ISSUE THREAD

**Issue by Kasper-M** [cloudstax/firecamp#83]
I try to set-up a cloudformation stack based on this quickstart cassandra template.
https://github.com/aws-quickstart/quickstart-cloudstax-nosql
The following resource(s) failed to create: [LambdaCustomResource]
Failed to create resource. Bad Request

Parameters:
zones: eu-west-1a,eu-west-1b,eu-west-1c
CassandraRelease: 3.11
FireCampRelease: 0.9.6

Based on the error message from AWS I have no clue how to fix this error.
Does someone has any ideas?

**Comment by jazzl0ver** [comment]
Hi. Why are you setting up 0.9.6? Try the latest release - 1.0

**Comment by JuniusLuo** [comment]
Do you have the permission to create Lambda resource? 

Just triggered a run for quickstart cassandra template, it worked well.

**Comment by JuniusLuo** [comment]
Please run from https://aws.amazon.com/quickstart/architecture/cloudstax-nosql-db-for-cassandra/.

**Comment by Kasper-M** [comment]
> Hi. Why are you setting up 0.9.6? Try the latest release - 1.0

I used the latest release and this works. Thanks for your answers!
