### ISSUE TITLE
firecamp-autoscalegroup.template does not use AMI ID specified in the parent template (firecamp-existingvpc.template)

### ISSUE THREAD

**Issue by jazzl0ver** [cloudstax/firecamp#9]
Please, fix

**Comment by JuniusLuo** [comment]
Thanks! The AMI ID mapping should be in firecamp-autoscalegroup.template. So we don't need to define the mapping in multiple places, firecamp-master.template and firecamp-existingvpc.template. 

The AMI ID in firecamp-existingvpc.template is not used. Will remove it. Saw you created a pull request. If you want to remove it in your patch, it would be great.

**Comment by JuniusLuo** [comment]
The autoscalegroup template is shared by both existingvpc and master templates. The EC2 instance ImageId is not passed from the existingvpc template to the autoscalegroup template. Instead, the autoscalegroup template will select the ImageId based on the region and "NodeAMIOS" (default Amazon Linux AMI). The existingvpc template will call the autoscalgroup template to actually create the EC2 instances.

The other option is the existingvpc template selects the ImageId and passes to the autoscalegroup template. But the master template has to select the ImageId and passes to the autoscalegroup template as well. The AMI region map will be duplicated in the existingvpc and mater templates.

**Comment by jazzl0ver** [comment]
Got it. At first I decided you gonna delete existingvpc template. Thanks!

**Comment by cloudstax** [comment]
The fix from @jazzl0ver was merged.
